schema_version: 0.3
type: producer
identifier: krita
title: Krita
version: 1
copyright: Eoin O'Neill, Emmet O'Neill
creator: Eoin O'Neill, Emmet O'Neill
license: LGPLv2.1
language: en
tags:
  - Video
  - Audio
parameters:
  - identifier: frame_start
    title: Start Frame
    type: integer
    description: First frame of the acceptable playback range.
    default: 0
    mutable: true

  - identifier: frame_end
    title: End Frame
    type: integer
    description: Last frame of the acceptable playback range.
    default: 100
    mutable: true

  - identifier: limit_enabled
    title: Limit Enabled
    type: integer
    description: Whether the frame limiting feature should be enabled.
    default: 0
    mutable: true
